In [24]:
#Exercice 1
import numpy as np

#Cet algorithme devra faire partie d’une classe Algèbre
class Algèbre(object):
    """Classe qui permet de créer un entier et de faire des opérations algébrique avec cet entier"""
    def __init__(self,n):
        """data : l'entier n"""
        self.n=int(n) #Votre programme doit maintenant être capable d’accepter en entrée des arguments spécifiés en ligne de commande

    def get_n(self):
        return self.n
    
    def set_n(self,n):
        self.n=int(n)

#Ecrivez un programme qui calcule puis affiche la somme des n premiers entiers (de 0 à n, n inclus).
    def somme(self):
        """affiche la somme des n premiiers entiers de 0 à n. Avec n l'attribut de l'objet"""
        a=0
        for i in range(0,self.n+1):
            a=a+i
        print(a)
            
#Ajouter une nouvelle fonction factorielle à la classe. La fonction prendra un argument n en entrée.
    def factorielle(self,n):
        """retorune la factorielle du n. Avec n qui n'est pas l'attribut de l'objet, mais nimporte quelle n passé en argument de la méthode"""
        n=int(n) #Votre programme doit maintenant être capable d’accepter en entrée des arguments spécifiés en ligne de commande
        if n==1 or n==0:
            return 1
        a=1
        for i in range(2,n+1):
            a=a*i
        print(a)
    
    
def main():
    nombre=Algèbre(3)
    nombre.somme()
    nombre.factorielle(nombre.n)
    
    nombre2=Algèbre(input("Entrez votre N!\n"))
    nombre2.somme()
    nombre2.factorielle(nombre2.n)
    

In [25]:
main()

6
6
Entrez votre N!
4
10
24


In [136]:
#Exercice 2

import math

class Vecteur(object):
    """permet de créer des objects vecteurs et de faire des opérations sur ces vecteurs"""
    def __init__(self,x,y,z):
        """data:le vecteur vect"""
        #doivent pouvoir être effectuées : — créer un vecteur avec pour coordonnées [0, 0, 0] ;
                                            #— créer un vecteur avec les coordonnées x, y, z fournies en argument au c
        #On ne peut créer un vecteur qu'avec un constructeur et on ne peut pas à la fois créer un vecteur nulle par défaut et l'initialiser avec les arguments
        #l'opération de création d'un vecteur peut être effectuer en mettant en argument (0,0,0)
        self.vect=np.array([[x],[y],[z]])

    def get_vecteur(self):
        return self.vect
    
    def set_vecteur(self,x,y,z):
        self.vect=np.array([[x],[y],[z]])
    
    def additionner(self,v:Vecteur):
        """additionne le vecteur duquel est appelé la méthode et le vecteur passé en argument"""
        vect_somme=Vecteur(self.vect[0,0]+v.vect[0,0],self.vect[1,0]+v.vect[1,0],self.vect[2,0]+v.vect[2,0])
        return vect_somme
                             
    def calculerNorme(self):
        """retourne la norme du vecteur duquel est appelé la méthode"""
        return math.sqrt(self.vect[0,0]**2 + self.vect[1,0]**2 + self.vect[2,0]**2)
                        
    def calculerProduitScalaire(self,v:Vecteur):
        """retourne le produit scalaire entre le vecteur duquel est appelé la méthode et le vecteur passé en argument"""
        return np.dot(np.transpose(self.vect),v.vect)

    def tourner(self,alpha):
        """retourne un vecteur correspondant à une rotation de l'angle donné en arguments selon z, du vecteur duquel est appelé la méthode"""
        norme=self.calculerNorme()
        if norme == 0:
            return Vecteur(0,0,0)
        theta=np.arctan2(self.vect[1,0]/norme,self.vect[0,0]/norme)
        new_vect=Vecteur(norme*math.cos(theta+alpha),norme*math.sin(theta+alpha),self.vect[2,0])
        return new_vect
    
    def afficher(self):
        """affiche le vecteur duquel est appelé la méthode"""
        print(self.vect)

def main2():
    v1=Vecteur(1,0,0)
    v2=Vecteur(1,1,0)
    v3=Vecteur(0,0,0)
    v3.afficher()
    print("------")
    
    v3=v1.additionner(v2)
    v3.afficher()
    print("------")
    
    print(v1.calculerNorme())
    print(v1.calculerProduitScalaire(v2))
    print("------")
    
    v3=v1.tourner(math.pi/2)
    v3.afficher()
    



In [137]:
main2()

[[0]
 [0]
 [0]]
------
[[2]
 [1]
 [0]]
------
1.0
[[1]]
------
[[6.123234e-17]
 [1.000000e+00]
 [0.000000e+00]]


In [138]:
#Exercice 3

class Triangle(object):
    """permet de créer des objects triangles et de faire des opérations sur ces triangles"""
    def __init__(self,x1,y1,z1,x2,y2,z2,x3,y3,z3):
        """data : 3 Vecteur"""
        self.p1=Vecteur(x1,y1,z1)
        self.p2=Vecteur(x2,y2,z2)
        self.p3=Vecteur(x3,y3,z3)
        
    def get_triangle(self):
        return [self.p1,self.p2,self.p3]
    
    def set_triangle(self,v1:Vecteur,v2:Vecteur,v3:Vecteur):
        self.p1=v1
        self.p2=v2
        self.p3=v3
        
    def tourner(self,alpha):
        """applique une rotation de l'angle donné en arguments selon z, au triangle duquel est appelé la méthode"""
        self.p1=self.p1.tourner(alpha)
        self.p2=self.p2.tourner(alpha)
        self.p3=self.p3.tourner(alpha)
        
    def afficher(self):
        """affiche les coordonnées du triangle duquel est appelé la méthode"""
        self.p1.afficher()
        self.p2.afficher()
        self.p3.afficher()
        
    def deplacer(self,v:Vecteur):
        """déplace le trinagle selune une translation du vecteur donné en argument"""
        self.p1=self.p1.additionner(v)
        self.p2=self.p2.additionner(v)
        self.p3=self.p3.additionner(v)

def main3():
    tr=Triangle(0,0,0,1,0,0,0,1,0)
    tr.tourner(math.pi/2)
    tr.afficher()
    print("--------")
    v4=Vecteur(0,-1,0)
    tr.deplacer(v4)
    tr.afficher()

In [139]:
main3()

[[0]
 [0]
 [0]]
[[6.123234e-17]
 [1.000000e+00]
 [0.000000e+00]]
[[-1.0000000e+00]
 [ 1.2246468e-16]
 [ 0.0000000e+00]]
--------
[[ 0]
 [-1]
 [ 0]]
[[6.123234e-17]
 [0.000000e+00]
 [0.000000e+00]]
[[-1.]
 [-1.]
 [ 0.]]


In [140]:
#Exercice 4

class Couleur(object):
    """permet de créer un objet couleur"""
    def __init__(self,r:int,v:int,b:int):
        """deta : liste des composantes r,v,b"""
        self.couleur=[r,v,b]
        
    def get_couleur(self):
        return self.couleur
    
    
    def set_couleur(self,r,v,b):
        self.couleur=[r,v,b]
        

class Objet3D(object):
    """permet de créer des objets 3D, de modifier son emplacement et sa composition"""
    def __init__(self, centre:Vecteur, couleur:Couleur):
        self.centre=centre
        self.couleur=couleur
        self.liste_triangle=[]
        
    def get_objet(self):
        return [self.centre,self.couleur,self.liste_triangle]
    
    def set_objet(self,centre:Vecteur, couleur:Couleur):
        self.centre=centre
        self.couleur=couleur
        
    def afficher(self):
        """afficher tous les vecteurs qui composent l'objet"""
        for i in range(0,len(self.liste_triangle)):
            self.liste_triangle[i].afficher()
            
    def ajouter(self, tr:Triangle):
        """Ajoute un triangle à l'objet"""
        self.liste_triangle.append(tr)
        
        
    def deplacer(self,v:Vecteur):
        """translate l'objet duiquel est appelé la méthode, du vecteur donné en paramètre"""
        for i in range(0,len(self.liste_triangle)):
            self.liste_triangle[i].deplacer(v)
            
    
def main4():
    obj1=Objet3D(Vecteur(0,0,0),Couleur(255,255,0))
    obj1.ajouter(Triangle(0,0,0,1,0,0,0,1,0))
    obj1.afficher()
    print("---------")
    obj1.deplacer(Vecteur(0,-1,0))
    obj1.afficher()
    

In [141]:
main4()

[[0]
 [0]
 [0]]
[[1]
 [0]
 [0]]
[[0]
 [1]
 [0]]
---------
[[ 0]
 [-1]
 [ 0]]
[[ 1]
 [-1]
 [ 0]]
[[0]
 [0]
 [0]]


In [143]:
#Exercice 5
import random

class De(object):
    def __init__(self):
        self.val
        
    def get_val_de(self):
        return self.val
    
    def set_val_de(self,n:int):
        self.val=n
        
    def alea(self):
        self.set_val_de(random.randint(1, 6))
        

class Joueur(object):
    def __init__(self):
        self.combinaison=[]
        
    def get_combinaison(self):
        return self.combinaison
    
    def set_combinaison(self,a,b,c):
        self.combinaison=[a,b,c]
        
    def lancer(self,de):
        de.alea()
        
    def relancer(self):
        n1=input("taper1 si vous souhairer relancer un dé ou 2 si vous souhaiter relancer 2 dés")
        if n1==1:
            n2=input("quelle dé souhaité vous rejouer ? 1, 2 ou 3 ?")
            
    def acquerir_val(self,de):
        n=de.get_val_de()
        return n
        
        
class Jeu(object):
    def __init__(self,de1:De,de2:De,dee:De,liste_joueur):
        self.de1=de1
        self.de2=de2
        self.de3=de3
        self.liste_joueur=liste_joueur
def main5():
    print("all rieghts")

In [144]:
main5()

all rieghts
